-- test git integration
-- Initial the env in Snowflake
USE ROLE SYSADMIN;

-- CREATE databases for data engineers 
CREATE DATABASE IF NOT EXISTS DB_ADE_DATAENG_DEV;
CREATE DATABASE IF NOT EXISTS DB_ADE_DATAENG_SIT;
CREATE DATABASE IF NOT EXISTS DB_ADE_DATAENG_UAT;


use database DB_ADE_DATAENG_DEV;
CREATE SCHEMA IF NOT EXISTS BRONZE_DE;
CREATE SCHEMA IF NOT EXISTS SILVER_DE;
CREATE SCHEMA IF NOT EXISTS GOLD_DE;
CREATE SCHEMA IF NOT EXISTS BRONZE_DE_WORKING;
CREATE SCHEMA IF NOT EXISTS SILVER_DE_WORKING;
CREATE SCHEMA IF NOT EXISTS GOLD_DE_WORKING;
CREATE SCHEMA IF NOT EXISTS INTG;


use database DB_ADE_DATAENG_SIT;;
CREATE SCHEMA IF NOT EXISTS BRONZE_DE;
CREATE SCHEMA IF NOT EXISTS SILVER_DE;
CREATE SCHEMA IF NOT EXISTS GOLD_DE;
CREATE SCHEMA IF NOT EXISTS BRONZE_DE_WORKING;
CREATE SCHEMA IF NOT EXISTS SILVER_DE_WORKING;
CREATE SCHEMA IF NOT EXISTS GOLD_DE_WORKING;
CREATE SCHEMA IF NOT EXISTS INTG;

use database DB_ADE_DATAENG_UAT;;
CREATE SCHEMA IF NOT EXISTS BRONZE_DE;
CREATE SCHEMA IF NOT EXISTS SILVER_DE;
CREATE SCHEMA IF NOT EXISTS GOLD_DE;
CREATE SCHEMA IF NOT EXISTS BRONZE_DE_WORKING;
CREATE SCHEMA IF NOT EXISTS SILVER_DE_WORKING;
CREATE SCHEMA IF NOT EXISTS GOLD_DE_WORKING;
CREATE SCHEMA IF NOT EXISTS INTG;

